<a href="https://colab.research.google.com/github/Madhuanabala/deepak-bhaiya/blob/feature-selection/Atompair_SIRT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_selection import VarianceThreshold, SelectKBest, mutual_info_classif
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('/content/AtomPairs2D.csv')
data

,Name,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,AD2D8,AD2D9,...,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780,BioactivityClass
0,CHEMBL420311,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Active
1,CHEMBL115600,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Active
2,CHEMBL112265,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
3,CHEMBL446446,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Active
4,CHEMBL171137,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
929,CHEMBL4749004,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
930,CHEMBL5416344,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
931,CHEMBL5424599,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
932,CHEMBL5420622,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Inactive

In [8]:
print(data.columns)
data.loc[data[' BioactivityClass'] == 'Active', ' BioactivityClass'] = 'P'
data.loc[data[' BioactivityClass'] == 'Inactive', ' BioactivityClass'] = 'N'
data

Index(['Name', 'AD2D1', 'AD2D2', 'AD2D3', 'AD2D4', 'AD2D5', 'AD2D6', 'AD2D7',
       'AD2D8', 'AD2D9',
       ...
       'AD2D772', 'AD2D773', 'AD2D774', 'AD2D775', 'AD2D776', 'AD2D777',
       'AD2D778', 'AD2D779', 'AD2D780', ' BioactivityClass'],
      dtype='object', length=782)

,Name,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,AD2D8,AD2D9,...,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780,BioactivityClass
0,CHEMBL420311,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,P
1,CHEMBL115600,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,P
2,CHEMBL112265,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
3,CHEMBL446446,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,P
4,CHEMBL171137,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
929,CHEMBL4749004,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
930,CHEMBL5416344,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
931,CHEMBL5424599,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
932,CHEMBL5420622,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N

In [9]:
data[' BioactivityClass'].replace('P', '1', inplace=True)
data[' BioactivityClass'].replace('N', '0', inplace=True)
data.rename(columns = {" BioactivityClass": " BioactivityClass"}, inplace = True)
data

/tmp/ipython-input-9-1827563494.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[' BioactivityClass'].replace('P', '1', inplace=True)
/tmp/ipython-input-9-1827563494.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[' BioactivityClass'].replace('N', '0', inplace=True)

,Name,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,AD2D8,AD2D9,...,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780,BioactivityClass
0,CHEMBL420311,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,CHEMBL115600,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,CHEMBL112265,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL446446,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,CHEMBL171137,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
929,CHEMBL4749004,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
930,CHEMBL5416344,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
931,CHEMBL5424599,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
932,CHEMBL5420622,1,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data.isnull().sum().sum()
data.dropna(inplace =True)
data.isnull().sum().sum()
data1 = data.iloc[:,1:781]
data1
data2 = data.iloc[:,-1]
data1
data2

0      1
1      1
2      0
3      1
4      0
      ..
928    0
929    0
930    0
931    0
932    0
Name:  BioactivityClass, Length: 933, dtype: object

In [13]:
from sklearn.feature_selection import VarianceThreshold
threshold = VarianceThreshold(threshold=.1)
def variance_threshold_selector(data1, threshold=0.10):
    selector = VarianceThreshold(threshold)
    selector.fit(data1)
    return data[data1.columns[selector.get_support(indices=True)]]
data1_HV = variance_threshold_selector(data1)
data1_HV
data2_HV = pd.merge(data1_HV,data2,left_index=True,right_index=True)
data2_HV

,AD2D4,AD2D12,AD2D13,AD2D82,AD2D90,AD2D91,AD2D92,AD2D93,AD2D102,AD2D160,...,AD2D703,AD2D704,AD2D705,AD2D706,AD2D714,AD2D715,AD2D716,AD2D726,AD2D727,BioactivityClass
0,0,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,1,0,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,0,0,0,0,0,1,1,0,0,0,...,1,1,1,0,0,0,0,0,0,0
929,0,0,0,0,0,0,1,0,0,0,...,1,1,1,0,0,0,0,0,0,0
930,1,1,0,0,1,1,1,1,1,1,...,1,1,1,0,1,1,1,0,1,0
931,1,1,0,0,1,1,0,1,1,1,...,1,1,0,0,1,1,1,0,0,0
932,1,1,0,0,1,1,0,1,1,1,...,1,1,1,0,1,1,1,0,0,0

In [19]:
correlated_features_1 = set()
corr_matrix_class = data2_HV.drop(columns=[' BioactivityClass']).corr()


for i in range(len(corr_matrix_class.columns)):
    for j in range(i):
        if abs(corr_matrix_class.iloc[i, j]) > 0.9:
            colname = corr_matrix_class.columns[i]
            correlated_features_1.add(colname)
correlated_features_1
def remove_correlated_features(features, data):
    for x in features:
        data.drop(x, axis=1, inplace=True)
    return data
data3 = remove_correlated_features(correlated_features_1, data2_HV)
data3

,AD2D4,AD2D12,AD2D13,AD2D82,AD2D91,AD2D92,AD2D93,AD2D102,AD2D169,AD2D170,...,AD2D703,AD2D704,AD2D705,AD2D706,AD2D714,AD2D715,AD2D716,AD2D726,AD2D727,BioactivityClass
0,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,0,0,0,0,1,1,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
929,0,0,0,0,0,1,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
930,1,1,0,0,1,1,1,1,0,0,...,1,1,1,0,1,1,1,0,1,0
931,1,1,0,0,1,0,1,1,0,0,...,1,1,0,0,1,1,1,0,0,0
932,1,1,0,0,1,0,1,1,0,0,...,1,1,1,0,1,1,1,0,0,0

In [21]:
data3.to_csv('ap2d2.csv')
X = data3.iloc[:,1:52]  #independent columns
X
y = data3.iloc[:,-1]
y

0      1
1      1
2      0
3      1
4      0
      ..
928    0
929    0
930    0
931    0
932    0
Name:  BioactivityClass, Length: 933, dtype: object

In [22]:
scaler = StandardScaler()
X_transform = scaler.fit_transform(X)
X_transform_pd = pd.DataFrame(X_transform, columns = X.columns)
X_transform_pd

,AD2D12,AD2D13,AD2D82,AD2D91,AD2D92,AD2D93,AD2D102,AD2D169,AD2D170,AD2D171,...,AD2D649,AD2D703,AD2D704,AD2D705,AD2D706,AD2D714,AD2D715,AD2D716,AD2D726,AD2D727
0,2.017586,-0.367473,-0.674936,-0.798024,0.528995,-0.736308,-0.634829,-0.722511,-0.9904,-0.391504,...,-0.514031,-2.231764,-1.546844,-1.977505,-0.713939,-0.400559,-0.698597,-0.821611,-0.487238,-0.475414
1,-0.495642,-0.367473,-0.674936,-0.798024,0.528995,-0.736308,-0.634829,-0.722511,-0.9904,-0.391504,...,-0.514031,-2.231764,-1.546844,-1.977505,-0.713939,-0.400559,-0.698597,-0.821611,-0.487238,-0.475414
2,-0.495642,-0.367473,-0.674936,-0.798024,0.528995,-0.736308,-0.634829,-0.722511,-0.9904,-0.391504,...,-0.514031,-2.231764,-1.546844,-1.977505,-0.713939,-0.400559,-0.698597,-0.821611,-0.487238,-0.475414
3,2.017586,-0.367473,-0.674936,-0.798024,0.528995,-0.736308,-0.634829,-0.722511,-0.9904,-0.391504,...,-0.514031,-2.231764,-1.546844,-1.977505,-0.713939,-0.400559,-0.698597,-0.821611,-0.487238,-0.475414
4,2.017586,-0.367473,-0.674936,-0.798024,-1.890378,-0.736308,1.575228,-0.722511,-0.9904,-0.391504,...,-0.514031,-2.231764,-1.546844,-1.977505,-0.713939,2.496509,-0.698597,-0.821611,-0.487238,-0.475414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,-0.495642,-0.367473,-0.674936,1.253095,0.528995,-0.736308,-0.634829,-0.722511,-0.9904,-0.391504,...,-0.514031,0.448076,0.646477,0.505688,-0.713939,-0.400559,-0.698597,-0.821611,-0.487238,-0.475414
929,-0.495642,-0.367473,-0.674936,-0.798024,0.528995,-0.736308,-0.634829,-0.722511,-0.9904,-0.391504,...,-0.514031,0.448076,0.646477,0.505688,-0.713939,-0.400559,-0.698597,-0.821611,-0.487238,-0.475414
930,2.017586,-0.367473,-0.674936,1.253095,0.528995,1.358128,1.575228,-0.722511,-0.9904,-0.391504,...,-0.514031,0.448076,0.646477,0.505688,-0.713939,2.496509,1.431440,1.217121,-0.487238,2.103430
931,2.017586,-0.367473,-0.674936,1.253095,-1.890378,1.358128,1.575228,-0.722511,-0.9904,-0.391504,...,-0.514031,0.448076,0.646477,-1.977505,-0.713939,2.496509,1.431440,1.217121,-0.487238,-0.475414
932,2.017586,-0.367473,-0.674936,1.253095,-1.890378,1.358128,1.575228,-0.722511,-0.9904,-0.391504,...,-0.514031,0.448076,0.646477,0.505688,-0.713939,2.496509,1.431440,1.217121,-0.487238,-0.475414

In [23]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
kBest = SelectKBest(mutual_info_classif, k = 10)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

kBest = SelectKBest(mutual_info_classif, k = 20)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

kBest = SelectKBest(mutual_info_classif, k = 30)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

(933, 30)

In [24]:
kBest.get_support(True)

array([ 1,  2,  4,  6,  7, 11, 12, 15, 16, 17, 18, 19, 20, 27, 28, 30, 31,
       32, 33, 34, 36, 37, 38, 39, 41, 45, 46, 47, 48, 50])

In [25]:
X_kBestFeatures = X.iloc[:, kBest.get_support(True)]
X_kBestFeatures.columns
f = kBest.get_support(1)
X_new = X[X.columns[f]]
X_new
data_scores = pd.DataFrame(kBest.scores_)
data_columns = pd.DataFrame(X.columns)
featureScores = pd.concat([data_columns, data_scores], axis = 1)

#naming the dataframe columns
featureScores.columns = ['Features', 'Scores']
featureScores

   Features    Scores
0    AD2D12  0.000000
1    AD2D13  0.002691
2    AD2D82  0.043615
3    AD2D91  0.000000
4    AD2D92  0.022119
5    AD2D93  0.000000
6   AD2D102  0.018554
7   AD2D169  0.009626
8   AD2D170  0.000000
9   AD2D171  0.000000
10  AD2D180  0.000000
11  AD2D247  0.025435
12  AD2D248  0.011878
13  AD2D258  0.000000
14  AD2D259  0.000000
15  AD2D325  0.008299
16  AD2D326  0.010961
17  AD2D336  0.005957
18  AD2D337  0.003184
19  AD2D403  0.031436
20  AD2D404  0.005515
21  AD2D414  0.000000
22  AD2D480  0.000000
23  AD2D481  0.000000
24  AD2D482  0.000000
25  AD2D483  0.000000
26  AD2D492  0.000000
27  AD2D548  0.002695
28  AD2D558  0.013257
29  AD2D559  0.000000
30  AD2D560  0.016528
31  AD2D561  0.032939
32  AD2D570  0.024815
33  AD2D626  0.002687
34  AD2D627  0.019141
35  AD2D628  0.000000
36  AD2D636  0.002273
37  AD2D637  0.019532
38  AD2D638  0.018147
39  AD2D639  0.045112
40  AD2D648  0.000000
41  AD2D649  0.018127
42  AD2D703  0.000212
43  AD2D704  0.000000
44  AD2D705  0.000000
45  AD2D706  0.028688
46  AD2D714  0.003346
47  AD2D715  0.015714
48  AD2D716  0.018240
49  AD2D726  0.000015
50  AD2D727  0.022713

In [26]:
Graph = (featureScores.nlargest(10, 'Scores'))
Graph
Graph = (featureScores.nlargest(20, 'Scores'))
Graph
Graph = (featureScores.nlargest(30, 'Scores'))
Graph

   Features    Scores
39  AD2D639  0.045112
2    AD2D82  0.043615
31  AD2D561  0.032939
19  AD2D403  0.031436
45  AD2D706  0.028688
11  AD2D247  0.025435
32  AD2D570  0.024815
50  AD2D727  0.022713
4    AD2D92  0.022119
37  AD2D637  0.019532
34  AD2D627  0.019141
6   AD2D102  0.018554
48  AD2D716  0.018240
38  AD2D638  0.018147
41  AD2D649  0.018127
30  AD2D560  0.016528
47  AD2D715  0.015714
28  AD2D558  0.013257
12  AD2D248  0.011878
16  AD2D326  0.010961
7   AD2D169  0.009626
15  AD2D325  0.008299
17  AD2D336  0.005957
20  AD2D404  0.005515
46  AD2D714  0.003346
18  AD2D337  0.003184
27  AD2D548  0.002695
1    AD2D13  0.002691
33  AD2D626  0.002687
36  AD2D636  0.002273

In [27]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
import pandas as pd
import matplotlib.pyplot as plt

# Ensure X is DataFrame and convert y to NumPy array
X = data3.iloc[:,1:52]  #independent columns
y_array = data3.iloc[:,-1].values

#Top 10 Features
k = 10
kBest = SelectKBest(mutual_info_classif, k=k)
# Pass X as DataFrame and y_array as NumPy array
X_new = kBest.fit_transform(X, y_array)
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]

# Step 2: Create and save top-k feature scores CSV
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')  # Sorted top-k features
Graph.to_csv(f'Atom2dFeatures_top{k}.csv', index=False)

# Step 3: Plot and save bar chart
data = pd.read_csv(f'Atom2dFeatures_top{k}.csv')
df = pd.DataFrame(data)
# X_labels = list(df.iloc[:, 0])
# Y_scores = list(df.iloc[:, 1])

plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"Atom Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

# Step 4: Combine selected features and target, save dataset
Atom_pair_2d_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
Atom_pair_2d_FS2.to_csv(f'Atom2d2_Trainset_top{k}.csv', index=False)


#Top 20 Features
k = 20
kBest = SelectKBest(mutual_info_classif, k=k)
X_new = kBest.fit_transform(X, y_array) # Use y_array
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')
Graph.to_csv(f'Atom2dFeatures_top{k}.csv', index=False)

data = pd.read_csv(f'Atom2dFeatures_top{k}.csv')
df = pd.DataFrame(data)
plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"Atom Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

Atom_pair_2d_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
Atom_pair_2d_FS2.to_csv(f'Atom2d2_Trainset_top{k}.csv', index=False)


#Top 30 Features
k = 30
kBest = SelectKBest(mutual_info_classif, k=k)
X_new = kBest.fit_transform(X, y_array) # Use y_array
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')
Graph.to_csv(f'Atom2dFeatures_top{k}.csv', index=False)

data = pd.read_csv(f'Atom2dFeatures_top{k}.csv')
df = pd.DataFrame(data)
plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"Atom Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

Atom_pair_2d_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
Atom_pair_2d_FS2.to_csv(f'Atom2d2_Trainset_top{k}.csv', index=False)