<a href="https://colab.research.google.com/github/Madhuanabala/deepak-bhaiya/blob/feature-selection/CDKE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_selection import VarianceThreshold, SelectKBest, mutual_info_classif
from sklearn.preprocessing import StandardScaler


data = pd.read_csv('/content/CDKextended.csv')
data

,Name,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,ExtFP8,ExtFP9,...,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024,BioactivityClass
0,CHEMBL420311,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,Active
1,CHEMBL115600,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,Active
2,CHEMBL112265,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,Inactive
3,CHEMBL446446,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,Active
4,CHEMBL171137,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,Inactive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
929,CHEMBL4749004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
930,CHEMBL5416344,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
931,CHEMBL5424599,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
932,CHEMBL5420622,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive

In [2]:
print(data.columns)
data.loc[data[' BioactivityClass'] == 'Active', ' BioactivityClass'] = 'P'
data.loc[data[' BioactivityClass'] == 'Inactive', ' BioactivityClass'] = 'N'
data

Index(['Name', 'ExtFP1', 'ExtFP2', 'ExtFP3', 'ExtFP4', 'ExtFP5', 'ExtFP6',
       'ExtFP7', 'ExtFP8', 'ExtFP9',
       ...
       'ExtFP1016', 'ExtFP1017', 'ExtFP1018', 'ExtFP1019', 'ExtFP1020',
       'ExtFP1021', 'ExtFP1022', 'ExtFP1023', 'ExtFP1024',
       ' BioactivityClass'],
      dtype='object', length=1026)

,Name,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,ExtFP8,ExtFP9,...,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024,BioactivityClass
0,CHEMBL420311,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,P
1,CHEMBL115600,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,P
2,CHEMBL112265,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,N
3,CHEMBL446446,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,P
4,CHEMBL171137,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
929,CHEMBL4749004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
930,CHEMBL5416344,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
931,CHEMBL5424599,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
932,CHEMBL5420622,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N

In [3]:
data[' BioactivityClass'].replace('P', '1', inplace=True)
data[' BioactivityClass'].replace('N', '0', inplace=True)
data.rename(columns = {" BioactivityClass": " BioactivityClass"}, inplace = True)
data

/tmp/ipython-input-3-1827563494.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[' BioactivityClass'].replace('P', '1', inplace=True)
/tmp/ipython-input-3-1827563494.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[' BioactivityClass'].replace('N', '0', inplace=True)

,Name,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,ExtFP8,ExtFP9,...,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024,BioactivityClass
0,CHEMBL420311,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
1,CHEMBL115600,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
2,CHEMBL112265,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,CHEMBL446446,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
4,CHEMBL171137,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
929,CHEMBL4749004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
930,CHEMBL5416344,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
931,CHEMBL5424599,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
932,CHEMBL5420622,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
data.isnull().sum().sum()
data.dropna(inplace =True)
data.isnull().sum().sum()
data1 = data.iloc[:,1:781]
data1
data2 = data.iloc[:,-1]
data1
data2
from sklearn.feature_selection import VarianceThreshold
threshold = VarianceThreshold(threshold=.1)
def variance_threshold_selector(data1, threshold=0.10):
    selector = VarianceThreshold(threshold)
    selector.fit(data1)
    return data[data1.columns[selector.get_support(indices=True)]]
data1_HV = variance_threshold_selector(data1)
data1_HV
data2_HV = pd.merge(data1_HV,data2,left_index=True,right_index=True)
data2_HV

,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP7,ExtFP9,ExtFP10,ExtFP11,ExtFP12,ExtFP13,...,ExtFP768,ExtFP772,ExtFP773,ExtFP774,ExtFP775,ExtFP776,ExtFP777,ExtFP779,ExtFP780,BioactivityClass
0,0,0,0,1,0,0,0,0,1,1,...,1,0,0,0,0,1,1,0,0,1
1,1,0,0,1,0,0,0,0,1,1,...,0,0,0,0,0,1,1,0,0,1
2,0,0,0,1,0,0,0,0,1,1,...,0,0,0,0,0,1,1,0,0,0
3,0,0,0,1,0,0,0,0,1,1,...,1,0,0,0,0,1,1,0,0,1
4,0,0,0,1,0,0,0,0,1,0,...,1,1,0,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,0,0,1,1,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,0,0
929,0,0,0,0,0,0,0,0,1,1,...,0,0,0,1,0,1,1,0,0,0
930,1,1,0,0,0,0,0,0,0,1,...,1,0,1,1,0,0,0,1,0,0
931,0,1,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
932,0,1,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0

In [6]:
correlated_features_1 = set()
corr_matrix_class = data2_HV.drop(columns=[' BioactivityClass']).corr()


for i in range(len(corr_matrix_class.columns)):
    for j in range(i):
        if abs(corr_matrix_class.iloc[i, j]) > 0.9:
            colname = corr_matrix_class.columns[i]
            correlated_features_1.add(colname)
correlated_features_1
def remove_correlated_features(features, data):
    for x in features:
        data.drop(x, axis=1, inplace=True)
    return data
data3 = remove_correlated_features(correlated_features_1, data2_HV)
data3
data3.to_csv('cdke.csv')
X = data3.iloc[:,1:52]  #independent columns
X
y = data3.iloc[:,-1]
y
scaler = StandardScaler()
X_transform = scaler.fit_transform(X)
X_transform_pd = pd.DataFrame(X_transform, columns = X.columns)
X_transform_pd

,ExtFP2,ExtFP3,ExtFP4,ExtFP7,ExtFP9,ExtFP10,ExtFP11,ExtFP12,ExtFP13,ExtFP14,...,ExtFP50,ExtFP52,ExtFP53,ExtFP55,ExtFP56,ExtFP57,ExtFP58,ExtFP59,ExtFP60,ExtFP61
0,-0.458385,-0.639817,1.299523,-0.495642,-0.771279,-0.451521,-0.475414,0.755452,1.076904,-0.386024,...,2.554250,1.211715,1.009693,0.840040,-0.458385,1.258764,1.583515,0.819782,-0.468623,-0.623212
1,-0.458385,-0.639817,1.299523,-0.495642,-0.771279,-0.451521,-0.475414,0.755452,1.076904,-0.386024,...,2.554250,1.211715,1.009693,0.840040,-0.458385,1.258764,1.583515,0.819782,-0.468623,-0.623212
2,-0.458385,-0.639817,1.299523,-0.495642,-0.771279,-0.451521,-0.475414,0.755452,1.076904,-0.386024,...,2.554250,1.211715,1.009693,0.840040,-0.458385,1.258764,1.583515,0.819782,-0.468623,-0.623212
3,-0.458385,-0.639817,1.299523,-0.495642,-0.771279,-0.451521,-0.475414,0.755452,1.076904,-0.386024,...,2.554250,1.211715,1.009693,0.840040,-0.458385,1.258764,1.583515,0.819782,-0.468623,-0.623212
4,-0.458385,-0.639817,1.299523,-0.495642,-0.771279,-0.451521,-0.475414,0.755452,-0.928588,-0.386024,...,2.554250,1.211715,1.009693,0.840040,-0.458385,1.258764,1.583515,0.819782,2.133910,-0.623212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,-0.458385,1.562947,1.299523,-0.495642,-0.771279,-0.451521,-0.475414,0.755452,1.076904,-0.386024,...,2.554250,-0.825276,1.009693,0.840040,-0.458385,1.258764,-0.631507,0.819782,-0.468623,-0.623212
929,-0.458385,-0.639817,-0.769513,-0.495642,-0.771279,-0.451521,-0.475414,0.755452,1.076904,-0.386024,...,-0.391504,1.211715,-0.990400,0.840040,-0.458385,1.258764,-0.631507,-1.219836,-0.468623,-0.623212
930,2.181573,-0.639817,-0.769513,-0.495642,-0.771279,-0.451521,-0.475414,-1.323712,1.076904,2.590510,...,2.554250,-0.825276,1.009693,-1.190419,-0.458385,1.258764,-0.631507,0.819782,-0.468623,-0.623212
931,2.181573,1.562947,-0.769513,-0.495642,-0.771279,-0.451521,-0.475414,-1.323712,-0.928588,-0.386024,...,2.554250,-0.825276,1.009693,0.840040,-0.458385,1.258764,-0.631507,-1.219836,-0.468623,-0.623212
932,2.181573,1.562947,-0.769513,-0.495642,-0.771279,-0.451521,-0.475414,-1.323712,-0.928588,-0.386024,...,2.554250,-0.825276,1.009693,0.840040,-0.458385,1.258764,-0.631507,-1.219836,-0.468623,-0.623212

In [7]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
kBest = SelectKBest(mutual_info_classif, k = 10)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

kBest = SelectKBest(mutual_info_classif, k = 20)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

kBest = SelectKBest(mutual_info_classif, k = 30)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape
kBest.get_support(True)
X_kBestFeatures = X.iloc[:, kBest.get_support(True)]
X_kBestFeatures.columns
f = kBest.get_support(1)
X_new = X[X.columns[f]]
X_new
data_scores = pd.DataFrame(kBest.scores_)
data_columns = pd.DataFrame(X.columns)
featureScores = pd.concat([data_columns, data_scores], axis = 1)

#naming the dataframe columns
featureScores.columns = ['Features', 'Scores']
featureScores

   Features    Scores
0    ExtFP2  0.016760
1    ExtFP3  0.000000
2    ExtFP4  0.007287
3    ExtFP7  0.003500
4    ExtFP9  0.000000
5   ExtFP10  0.000000
6   ExtFP11  0.010859
7   ExtFP12  0.010718
8   ExtFP13  0.000000
9   ExtFP14  0.016807
10  ExtFP15  0.010650
11  ExtFP16  0.014991
12  ExtFP17  0.000000
13  ExtFP19  0.000000
14  ExtFP20  0.000000
15  ExtFP21  0.021179
16  ExtFP22  0.002326
17  ExtFP23  0.026125
18  ExtFP24  0.000000
19  ExtFP25  0.000000
20  ExtFP26  0.000000
21  ExtFP27  0.044076
22  ExtFP28  0.000000
23  ExtFP29  0.005960
24  ExtFP30  0.019622
25  ExtFP31  0.004680
26  ExtFP32  0.026866
27  ExtFP33  0.017665
28  ExtFP34  0.000000
29  ExtFP36  0.008746
30  ExtFP37  0.004235
31  ExtFP38  0.012456
32  ExtFP39  0.004415
33  ExtFP40  0.000000
34  ExtFP41  0.016394
35  ExtFP42  0.000538
36  ExtFP43  0.000000
37  ExtFP45  0.000000
38  ExtFP46  0.000000
39  ExtFP47  0.004012
40  ExtFP48  0.011003
41  ExtFP50  0.000000
42  ExtFP52  0.000000
43  ExtFP53  0.000000
44  ExtFP55  0.005466
45  ExtFP56  0.003195
46  ExtFP57  0.000000
47  ExtFP58  0.002118
48  ExtFP59  0.018056
49  ExtFP60  0.001244
50  ExtFP61  0.000000

In [8]:
Graph = (featureScores.nlargest(10, 'Scores'))
Graph
Graph = (featureScores.nlargest(20, 'Scores'))
Graph
Graph = (featureScores.nlargest(30, 'Scores'))
Graph

   Features    Scores
21  ExtFP27  0.044076
26  ExtFP32  0.026866
17  ExtFP23  0.026125
15  ExtFP21  0.021179
24  ExtFP30  0.019622
48  ExtFP59  0.018056
27  ExtFP33  0.017665
9   ExtFP14  0.016807
0    ExtFP2  0.016760
34  ExtFP41  0.016394
11  ExtFP16  0.014991
31  ExtFP38  0.012456
40  ExtFP48  0.011003
6   ExtFP11  0.010859
7   ExtFP12  0.010718
10  ExtFP15  0.010650
29  ExtFP36  0.008746
2    ExtFP4  0.007287
23  ExtFP29  0.005960
44  ExtFP55  0.005466
25  ExtFP31  0.004680
32  ExtFP39  0.004415
30  ExtFP37  0.004235
39  ExtFP47  0.004012
3    ExtFP7  0.003500
45  ExtFP56  0.003195
16  ExtFP22  0.002326
47  ExtFP58  0.002118
49  ExtFP60  0.001244
35  ExtFP42  0.000538

In [9]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
import pandas as pd
import matplotlib.pyplot as plt

# Ensure X is DataFrame and convert y to NumPy array
X = data3.iloc[:,1:52]  #independent columns
y_array = data3.iloc[:,-1].values

#Top 10 Features
k = 10
kBest = SelectKBest(mutual_info_classif, k=k)
# Pass X as DataFrame and y_array as NumPy array
X_new = kBest.fit_transform(X, y_array)
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]

# Step 2: Create and save top-k feature scores CSV
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')  # Sorted top-k features
Graph.to_csv(f'CDKetendedFeatures_top{k}.csv', index=False)

# Step 3: Plot and save bar chart
data = pd.read_csv(f'CDKetendedFeatures_top{k}.csv')
df = pd.DataFrame(data)
# X_labels = list(df.iloc[:, 0])
# Y_scores = list(df.iloc[:, 1])

plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"CDKetended Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

# Step 4: Combine selected features and target, save dataset
Atom_pair_2d_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
Atom_pair_2d_FS2.to_csv(f'CDKetended2_Trainset_top{k}.csv', index=False)


#Top 20 Features
k = 20
kBest = SelectKBest(mutual_info_classif, k=k)
X_new = kBest.fit_transform(X, y_array) # Use y_array
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')
Graph.to_csv(f'CDKetendedFeatures_top{k}.csv', index=False)

data = pd.read_csv(f'CDKetendedFeatures_top{k}.csv')
df = pd.DataFrame(data)
plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"CDKetended Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

Atom_pair_2d_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
Atom_pair_2d_FS2.to_csv(f'CDKetended2_Trainset_top{k}.csv', index=False)


#Top 30 Features
k = 30
kBest = SelectKBest(mutual_info_classif, k=k)
X_new = kBest.fit_transform(X, y_array) # Use y_array
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')
Graph.to_csv(f'CDKetendedFeatures_top{k}.csv', index=False)

data = pd.read_csv(f'CDKetendedFeatures_top{k}.csv')
df = pd.DataFrame(data)
plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"CDKetended Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

Atom_pair_2d_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
Atom_pair_2d_FS2.to_csv(f'CDKetended2_Trainset_top{k}.csv', index=False)