<a href="https://colab.research.google.com/github/Madhuanabala/deepak-bhaiya/blob/feature-selection/Kleorath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_selection import VarianceThreshold, SelectKBest, mutual_info_classif
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('/content/KlekotaRoth.csv')
data

,Name,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,KRFP8,KRFP9,...,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860,BioactivityClass
0,CHEMBL420311,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Active
1,CHEMBL115600,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Active
2,CHEMBL112265,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
3,CHEMBL446446,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Active
4,CHEMBL171137,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
929,CHEMBL4749004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
930,CHEMBL5416344,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
931,CHEMBL5424599,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive
932,CHEMBL5420622,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Inactive

In [3]:
print(data.columns)
data.loc[data[' BioactivityClass'] == 'Active', ' BioactivityClass'] = 'P'
data.loc[data[' BioactivityClass'] == 'Inactive', ' BioactivityClass'] = 'N'
data

Index(['Name', 'KRFP1', 'KRFP2', 'KRFP3', 'KRFP4', 'KRFP5', 'KRFP6', 'KRFP7',
       'KRFP8', 'KRFP9',
       ...
       'KRFP4852', 'KRFP4853', 'KRFP4854', 'KRFP4855', 'KRFP4856', 'KRFP4857',
       'KRFP4858', 'KRFP4859', 'KRFP4860', ' BioactivityClass'],
      dtype='object', length=4862)

,Name,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,KRFP8,KRFP9,...,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860,BioactivityClass
0,CHEMBL420311,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,P
1,CHEMBL115600,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,P
2,CHEMBL112265,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
3,CHEMBL446446,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,P
4,CHEMBL171137,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
929,CHEMBL4749004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
930,CHEMBL5416344,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
931,CHEMBL5424599,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
932,CHEMBL5420622,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N

In [4]:
data[' BioactivityClass'].replace('P', '1', inplace=True)
data[' BioactivityClass'].replace('N', '0', inplace=True)
data.rename(columns = {" BioactivityClass": " BioactivityClass"}, inplace = True)
data

/tmp/ipython-input-4-1827563494.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[' BioactivityClass'].replace('P', '1', inplace=True)
/tmp/ipython-input-4-1827563494.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[' BioactivityClass'].replace('N', '0', inplace=True)

,Name,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,KRFP8,KRFP9,...,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860,BioactivityClass
0,CHEMBL420311,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,CHEMBL115600,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,CHEMBL112265,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL446446,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,CHEMBL171137,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,CHEMBL4793948,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
929,CHEMBL4749004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
930,CHEMBL5416344,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
931,CHEMBL5424599,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
932,CHEMBL5420622,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
data.isnull().sum().sum()
data.dropna(inplace =True)
data.isnull().sum().sum()
data1 = data.iloc[:,1:781]
data1
data2 = data.iloc[:,-1]
data1
data2

0      1
1      1
2      0
3      1
4      0
      ..
928    0
929    0
930    0
931    0
932    0
Name:  BioactivityClass, Length: 933, dtype: object

In [6]:
from sklearn.feature_selection import VarianceThreshold
threshold = VarianceThreshold(threshold=.1)
def variance_threshold_selector(data1, threshold=0.10):
    selector = VarianceThreshold(threshold)
    selector.fit(data1)
    return data[data1.columns[selector.get_support(indices=True)]]
data1_HV = variance_threshold_selector(data1)
data1_HV
data2_HV = pd.merge(data1_HV,data2,left_index=True,right_index=True)
data2_HV

,KRFP1,KRFP14,KRFP16,KRFP20,KRFP297,KRFP298,KRFP302,KRFP303,KRFP314,KRFP341,...,KRFP467,KRFP480,KRFP504,KRFP506,KRFP605,KRFP647,KRFP669,KRFP677,KRFP678,BioactivityClass
0,1,0,0,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,1,0,0,1,1,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,1
2,1,0,0,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
4,1,0,0,1,1,1,1,0,0,1,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
929,0,0,0,0,1,0,0,0,0,1,...,1,1,0,0,0,0,0,1,0,0
930,1,0,0,0,1,1,0,0,0,1,...,1,0,1,0,1,0,0,1,0,0
931,0,0,0,0,1,0,0,0,0,1,...,1,0,1,0,0,0,0,1,0,0
932,0,0,0,0,1,0,0,0,0,1,...,1,0,1,0,0,0,1,1,0,0

In [7]:
correlated_features_1 = set()
corr_matrix_class = data2_HV.drop(columns=[' BioactivityClass']).corr()


for i in range(len(corr_matrix_class.columns)):
    for j in range(i):
        if abs(corr_matrix_class.iloc[i, j]) > 0.9:
            colname = corr_matrix_class.columns[i]
            correlated_features_1.add(colname)
correlated_features_1
def remove_correlated_features(features, data):
    for x in features:
        data.drop(x, axis=1, inplace=True)
    return data
data3 = remove_correlated_features(correlated_features_1, data2_HV)
data3

,KRFP1,KRFP14,KRFP16,KRFP20,KRFP297,KRFP298,KRFP341,KRFP344,KRFP346,KRFP383,KRFP387,KRFP401,KRFP466,KRFP504,KRFP506,KRFP605,KRFP647,KRFP669,KRFP677,BioactivityClass
0,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1
1,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,1
2,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1
4,1,0,0,1,1,1,1,1,0,0,0,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
929,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,1,0
930,1,0,0,0,1,1,1,1,0,1,0,1,0,1,0,1,0,0,1,0
931,0,0,0,0,1,0,1,1,0,1,0,1,0,1,0,0,0,0,1,0
932,0,0,0,0,1,0,1,1,0,1,0,1,0,1,0,0,0,1,1,0

In [8]:
data3.to_csv('kr.csv')
X = data3.iloc[:,1:52]  #independent columns
X
y = data3.iloc[:,-1]
y

0      1
1      1
2      0
3      1
4      0
      ..
928    0
929    0
930    0
931    0
932    0
Name:  BioactivityClass, Length: 933, dtype: object

In [9]:
scaler = StandardScaler()
X_transform = scaler.fit_transform(X)
X_transform_pd = pd.DataFrame(X_transform, columns = X.columns)
X_transform_pd

,KRFP14,KRFP16,KRFP20,KRFP297,KRFP298,KRFP341,KRFP344,KRFP346,KRFP383,KRFP387,KRFP401,KRFP466,KRFP504,KRFP506,KRFP605,KRFP647,KRFP669,KRFP677,BioactivityClass
0,-0.387855,-0.548867,1.377503,0.512364,1.187793,1.036018,1.336067,-0.649812,-0.606659,-0.418405,-0.367473,-0.456672,-0.517362,-0.404155,-0.371221,-0.608312,-1.273101,-1.296547,2.370026
1,-0.387855,-0.548867,1.377503,0.512364,1.187793,1.036018,1.336067,-0.649812,-0.606659,-0.418405,-0.367473,-0.456672,-0.517362,-0.404155,-0.371221,-0.608312,0.785484,-1.296547,2.370026
2,-0.387855,-0.548867,1.377503,0.512364,1.187793,1.036018,1.336067,-0.649812,-0.606659,-0.418405,-0.367473,-0.456672,-0.517362,-0.404155,-0.371221,-0.608312,-1.273101,-1.296547,-0.421936
3,-0.387855,-0.548867,1.377503,0.512364,1.187793,1.036018,1.336067,1.538906,-0.606659,-0.418405,-0.367473,-0.456672,-0.517362,-0.404155,-0.371221,-0.608312,-1.273101,-1.296547,2.370026
4,-0.387855,-0.548867,1.377503,0.512364,1.187793,1.036018,1.336067,-0.649812,-0.606659,-0.418405,-0.367473,2.189756,-0.517362,-0.404155,-0.371221,1.643892,0.785484,-1.296547,-0.421936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,-0.387855,-0.548867,-0.725951,-1.951737,-0.841897,-0.965234,-0.748466,-0.649812,-0.606659,-0.418405,-0.367473,-0.456672,-0.517362,-0.404155,-0.371221,-0.608312,-1.273101,0.771279,-0.421936
929,-0.387855,-0.548867,-0.725951,0.512364,-0.841897,1.036018,-0.748466,-0.649812,1.648372,2.390027,-0.367473,-0.456672,-0.517362,-0.404155,-0.371221,-0.608312,-1.273101,0.771279,-0.421936
930,-0.387855,-0.548867,-0.725951,0.512364,1.187793,1.036018,1.336067,-0.649812,1.648372,-0.418405,2.721287,-0.456672,1.932884,-0.404155,2.693815,-0.608312,-1.273101,0.771279,-0.421936
931,-0.387855,-0.548867,-0.725951,0.512364,-0.841897,1.036018,1.336067,-0.649812,1.648372,-0.418405,2.721287,-0.456672,1.932884,-0.404155,-0.371221,-0.608312,-1.273101,0.771279,-0.421936
932,-0.387855,-0.548867,-0.725951,0.512364,-0.841897,1.036018,1.336067,-0.649812,1.648372,-0.418405,2.721287,-0.456672,1.932884,-0.404155,-0.371221,-0.608312,0.785484,0.771279,-0.421936

In [10]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
kBest = SelectKBest(mutual_info_classif, k = 10)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

kBest = SelectKBest(mutual_info_classif, k = 20)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

kBest = SelectKBest(mutual_info_classif, k = 30)
X_kBestFeatures = kBest.fit_transform(X,y)
X_kBestFeatures.shape

/usr/local/lib/python3.11/dist-packages/sklearn/feature_selection/_univariate_selection.py:783: UserWarning: k=20 is greater than n_features=19. All the features will be returned.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/feature_selection/_univariate_selection.py:783: UserWarning: k=30 is greater than n_features=19. All the features will be returned.
  warnings.warn(

(933, 19)

In [11]:
kBest.get_support(True)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [12]:
X_kBestFeatures = X.iloc[:, kBest.get_support(True)]
X_kBestFeatures.columns
f = kBest.get_support(1)
X_new = X[X.columns[f]]
X_new
data_scores = pd.DataFrame(kBest.scores_)
data_columns = pd.DataFrame(X.columns)
featureScores = pd.concat([data_columns, data_scores], axis = 1)

#naming the dataframe columns
featureScores.columns = ['Features', 'Scores']
featureScores

             Features    Scores
0              KRFP14  0.009281
1              KRFP16  0.016177
2              KRFP20  0.024486
3             KRFP297  0.031276
4             KRFP298  0.053439
5             KRFP341  0.046270
6             KRFP344  0.026190
7             KRFP346  0.000000
8             KRFP383  0.052632
9             KRFP387  0.006115
10            KRFP401  0.011001
11            KRFP466  0.000000
12            KRFP504  0.002232
13            KRFP506  0.000000
14            KRFP605  0.017800
15            KRFP647  0.005912
16            KRFP669  0.020592
17            KRFP677  0.019062
18   BioactivityClass  0.425193

In [13]:
Graph = (featureScores.nlargest(10, 'Scores'))
Graph
Graph = (featureScores.nlargest(20, 'Scores'))
Graph
Graph = (featureScores.nlargest(30, 'Scores'))
Graph

             Features    Scores
18   BioactivityClass  0.425193
4             KRFP298  0.053439
8             KRFP383  0.052632
5             KRFP341  0.046270
3             KRFP297  0.031276
6             KRFP344  0.026190
2              KRFP20  0.024486
16            KRFP669  0.020592
17            KRFP677  0.019062
14            KRFP605  0.017800
1              KRFP16  0.016177
10            KRFP401  0.011001
0              KRFP14  0.009281
9             KRFP387  0.006115
15            KRFP647  0.005912
12            KRFP504  0.002232
7             KRFP346  0.000000
13            KRFP506  0.000000
11            KRFP466  0.000000

In [14]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
import pandas as pd
import matplotlib.pyplot as plt

# Ensure X is DataFrame and convert y to NumPy array
X = data3.drop(columns=[' BioactivityClass']) # independent columns, exclude target
y_array = data3.iloc[:,-1].values

#Top 10 Features
k = 10
kBest = SelectKBest(mutual_info_classif, k=min(k, X.shape[1])) # Use min to handle k > n_features
# Pass X as DataFrame and y_array as NumPy array
X_new = kBest.fit_transform(X, y_array)
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]

# Step 2: Create and save top-k feature scores CSV
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')  # Sorted top-k features
Graph.to_csv(f'kr_top{k}.csv', index=False)

# Step 3: Plot and save bar chart
data = pd.read_csv(f'kr_top{k}.csv')
df = pd.DataFrame(data)

plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"Atom Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

# Step 4: Combine selected features and target, save dataset
kr_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
kr_FS2.to_csv(f'kr_Trainset_top{k}.csv', index=False)


#Top 20 Features
k = 20
kBest = SelectKBest(mutual_info_classif, k=min(k, X.shape[1])) # Use min to handle k > n_features
X_new = kBest.fit_transform(X, y_array) # Use y_array
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')
Graph.to_csv(f'kr_top{k}.csv', index=False)

data = pd.read_csv(f'kr_top{k}.csv') # Corrected filename
df = pd.DataFrame(data)
plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"kleorath Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

kr_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
kr_FS2.to_csv(f'kr_Trainset_top{k}.csv', index=False)


#Top 30 Features
k = 30
kBest = SelectKBest(mutual_info_classif, k=min(k, X.shape[1])) # Use min to handle k > n_features
X_new = kBest.fit_transform(X, y_array) # Use y_array
selected_mask = kBest.get_support()
selected_columns = X.columns[selected_mask]
selected_scores = kBest.scores_[selected_mask]
featureScores = pd.DataFrame({'Features': selected_columns, 'Scores': selected_scores})
Graph = featureScores.nlargest(k, 'Scores')
Graph.to_csv(f'kr_top{k}.csv', index=False)

data = pd.read_csv(f'kr_top{k}.csv')
df = pd.DataFrame(data)
plt.figure(figsize=(10, 6))
plt.bar(df['Features'], df['Scores'], color='r')
plt.title(f"kleorath Feature_importance (Top {k})", fontweight="bold")
plt.xlabel("Features", fontweight='bold')
plt.ylabel("Scores", fontweight='bold')
plt.xticks(rotation=80, fontweight="bold")
plt.yticks(fontweight="bold")
plt.tight_layout()
plt.savefig(f"Features_top{k}.jpg", bbox_inches='tight')
plt.close()

kr_FS2 = pd.concat([X[selected_columns].reset_index(drop=True), data3.iloc[:,-1].reset_index(drop=True)], axis=1) # Use original y for concat
kr_FS2.to_csv(f'kr_Trainset_top{k}.csv', index=False)

/usr/local/lib/python3.11/dist-packages/sklearn/feature_selection/_univariate_selection.py:783: UserWarning: k=20 is greater than n_features=19. All the features will be returned.
  warnings.warn(

FileNotFoundError: [Errno 2] No such file or directory: 'Atom2dFeatures_top20.csv'